# Full reference https://github.com/foundry-rs/foundry/tree/master/config

[profile.default]
auto_detect_solc = false
fuzz = { max_test_rejects = 100_000, runs = 1_000 }
libs = ["lib"]
gas_reports = ["*"]
optimizer = true
optimizer_runs = 10_000
out = "out"
solc = "0.8.17"
src = "src"
test = "test/unit"
via_ir = true

[profile.default.optimizer_details.yulDetails]
optimizerSteps = ""

[profile.ci]
fuzz = { runs = 10_000 }
test = "test" # run all tests in CI, including integration tests
