# Full reference https://github.com/foundry-rs/foundry/tree/master/config

[profile.default]
auto_detect_solc = false
fuzz = { runs = 256 }
libs = ["lib"]
gas_reports = ["*"]
optimizer = true
optimizer_runs = 10_000
out = "out"
sender = "0x9aF2E2B7e57c1CD7C68C5C3796d8ea67e0018dB7"
solc = "0.8.17"
src = "src"
test = "test/unit/comptroller/get-protocol-fee"
tx_origin = "0x9aF2E2B7e57c1CD7C68C5C3796d8ea67e0018dB7"
via_ir = true

[profile.default.optimizer_details.yulDetails]
optimizerSteps = ""

[profile.ci]
fuzz = { runs = 1_000 }
test = "test"
verbosity = 4
