# Full reference https://github.com/foundry-rs/foundry/tree/master/config

[profile.default]
auto_detect_solc = false
libs = ["lib"]
fuzz_runs = 256
gas_reports = ["*"]
optimizer = true
optimizer_runs = 800
out = "out"
sender = "0x9aF2E2B7e57c1CD7C68C5C3796d8ea67e0018dB7"
solc = "0.8.15"
src = "src"
test = "test"
tx_origin = "0x9aF2E2B7e57c1CD7C68C5C3796d8ea67e0018dB7"

[profile.ci]
fuzz_runs = 10_000
verbosity = 4
