[profile.default]
  auto_detect_solc = false
  fs_permissions = [{ access = "read", path = "./optimized-out" }]
  fuzz = { max_test_rejects = 1_000_000, runs = 1_000 }
  libs = ["lib"]
  gas_reports = [
    "SablierV2Comptroller",
    "SablierV2LockupLinear",
    "SablierV2LockupPro",
  ]
  optimizer = true
  optimizer_runs = 10_000
  out = "out"
  script = "script"
  solc = "0.8.17"
  src = "src"
  test = "test"

# Speed up compilation and tests during development
[profile.lite]
  fuzz = { runs = 50 }
  optimizer = false

# Compile only the production code with IR
[profile.optimized]
  out = "optimized-out"
  test = "src"
  via_ir = true

# Test the optimized contracts without re-compiling them
[profile.test-optimized]
  fuzz = { runs = 5_000 }
  src = "test"
  verbosity = 4

[etherscan]
  ethereum = { key = "${ETHERSCAN_API_KEY}" }
  goerli = { key = "${ETHERSCAN_API_KEY}" }

[rpc_endpoints]
  ethereum = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
  localhost = "http://localhost:8545"
  goerli = "https://goerli.infura.io/v3/${INFURA_API_KEY}"
