name: "CI"

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

env:
  ETH_RPC_URL: "${{ secrets.ETH_RPC_URL }}"

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  lint:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"

      - name: "Install Node.js"
        uses: "actions/setup-node@v3"
        with:
          cache: "yarn"
          node-version: "lts/*"

      - name: "Install the Node.js dependencies"
        run: "yarn install --immutable"

      - name: "Lint the contracts"
        run: "yarn lint"

      - name: "Add lint summary"
        run: |
          echo "## Lint results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"
        with:
          submodules: "recursive"

      - name: "Install Foundry"
        uses: "foundry-rs/foundry-toolchain@v1"
        with:
          version: "nightly"

      # Always load the latest valid cache, and always create a new one with the updated cache.
      # When the fork tests are updated and there are new RPC requests, the RPC cache is updated as well.
      - name: "Cache RPC Responses"
        uses: "actions/cache@v3"
        with:
          key: "${{ runner.os }}-foundry-chain-fork-${{ github.sha }}"
          path: "~/.foundry/cache/rpc"
          restore-keys: |
            "${{ runner.os }}-foundry-chain-fork-"

      - name: "Show the Foundry config"
        run: "forge config"

      - name: "Run both the unit and the integration tests"
        run: "FOUNDRY_PROFILE=ci forge test"

      - name: "Add test summary"
        run: |
          echo "## Test results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
